-- Add multilingual columns to excursions table
ALTER TABLE excursions 
ADD COLUMN IF NOT EXISTS title_en TEXT,
ADD COLUMN IF NOT EXISTS title_tr TEXT,
ADD COLUMN IF NOT EXISTS title_de TEXT,
ADD COLUMN IF NOT EXISTS title_pl TEXT,
ADD COLUMN IF NOT EXISTS title_ar TEXT,
ADD COLUMN IF NOT EXISTS title_fa TEXT,

ADD COLUMN IF NOT EXISTS city_en TEXT,
ADD COLUMN IF NOT EXISTS city_tr TEXT,
ADD COLUMN IF NOT EXISTS city_de TEXT,
ADD COLUMN IF NOT EXISTS city_pl TEXT,
ADD COLUMN IF NOT EXISTS city_ar TEXT,
ADD COLUMN IF NOT EXISTS city_fa TEXT,

ADD COLUMN IF NOT EXISTS description_en TEXT,
ADD COLUMN IF NOT EXISTS description_tr TEXT,
ADD COLUMN IF NOT EXISTS description_de TEXT,
ADD COLUMN IF NOT EXISTS description_pl TEXT,
ADD COLUMN IF NOT EXISTS description_ar TEXT,
ADD COLUMN IF NOT EXISTS description_fa TEXT,

ADD COLUMN IF NOT EXISTS duration_en TEXT,
ADD COLUMN IF NOT EXISTS duration_tr TEXT,
ADD COLUMN IF NOT EXISTS duration_de TEXT,
ADD COLUMN IF NOT EXISTS duration_pl TEXT,
ADD COLUMN IF NOT EXISTS duration_ar TEXT,
ADD COLUMN IF NOT EXISTS duration_fa TEXT,

ADD COLUMN IF NOT EXISTS included_en TEXT,
ADD COLUMN IF NOT EXISTS included_tr TEXT,
ADD COLUMN IF NOT EXISTS included_de TEXT,
ADD COLUMN IF NOT EXISTS included_pl TEXT,
ADD COLUMN IF NOT EXISTS included_ar TEXT,
ADD COLUMN IF NOT EXISTS included_fa TEXT,

ADD COLUMN IF NOT EXISTS meeting_point_en TEXT,
ADD COLUMN IF NOT EXISTS meeting_point_tr TEXT,
ADD COLUMN IF NOT EXISTS meeting_point_de TEXT,
ADD COLUMN IF NOT EXISTS meeting_point_pl TEXT,
ADD COLUMN IF NOT EXISTS meeting_point_ar TEXT,
ADD COLUMN IF NOT EXISTS meeting_point_fa TEXT;

-- Add multilingual columns to faq table
ALTER TABLE faq
ADD COLUMN IF NOT EXISTS topic_en TEXT,
ADD COLUMN IF NOT EXISTS topic_tr TEXT,
ADD COLUMN IF NOT EXISTS topic_de TEXT,
ADD COLUMN IF NOT EXISTS topic_pl TEXT,
ADD COLUMN IF NOT EXISTS topic_ar TEXT,
ADD COLUMN IF NOT EXISTS topic_fa TEXT,

ADD COLUMN IF NOT EXISTS content_en TEXT,
ADD COLUMN IF NOT EXISTS content_tr TEXT,
ADD COLUMN IF NOT EXISTS content_de TEXT,
ADD COLUMN IF NOT EXISTS content_pl TEXT,
ADD COLUMN IF NOT EXISTS content_ar TEXT,
ADD COLUMN IF NOT EXISTS content_fa TEXT;
