/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-fixed": "#c9e6ff",
                "on-tertiary-container": "#381959",
                "on-secondary-fixed": "#001e2f",
                "surface-bright": "#39393b",
                "outline-variant": "#464554",
                "surface-variant": "#353437",
                "primary-fixed": "#e9ddff",
                "surface-container-lowest": "#0e0e10",
                "tertiary": "#dbb8ff",
                "error-container": "#93000a",
                "primary-container": "#a078ff",
                "surface-container-low": "#1c1b1d",
                "inverse-on-surface": "#313032",
                "surface-dim": "#131315",
                "on-tertiary-fixed": "#29074a",
                "background": "#131315",
                "on-primary": "#3c0091",
                "tertiary-fixed": "#efdbff",
                "on-tertiary-fixed-variant": "#573878",
                "surface-container-high": "#2a2a2c",
                "on-primary-fixed": "#23005c",
                "tertiary-fixed-dim": "#dbb8ff",
                "on-primary-fixed-variant": "#5516be",
                "secondary": "#89ceff",
                "primary": "#d0bcff",
                "surface-tint": "#d0bcff",
                "primary-fixed-dim": "#d0bcff",
                "surface-container": "#201f22",
                "outline": "#908fa0",
                "on-surface-variant": "#c7c4d7",
                "error": "#ffb4ab",
                "secondary-container": "#00a2e6",
                "inverse-primary": "#6d3bd7",
                "inverse-surface": "#e5e1e4",
                "on-error": "#690005",
                "surface": "#131315",
                "on-surface": "#e5e1e4",
                "tertiary-container": "#a482c8",
                "on-secondary-fixed-variant": "#004c6e",
                "on-background": "#e5e1e4",
                "surface-container-highest": "#353437",
                "on-tertiary": "#3f2160",
                "on-primary-container": "#340080",
                "on-secondary-container": "#00344e",
                "on-secondary": "#00344d",
                "secondary-fixed-dim": "#89ceff",
                "on-error-container": "#ffdad6"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "1.5rem",
                "full": "9999px"
            },
        },
    },
    plugins: [],
}
